/* OFFLINE is generated by scripts/build-offline.mjs from this production build. */
const CACHE_PREFIX = 'night-rail-offline-';
const CACHE_NAME = `${CACHE_PREFIX}${OFFLINE.version}`;
const ASSETS = new Set(OFFLINE.assets);
let preparing;

function prepare() {
  return preparing ||= (async () => {
    const cache = await caches.open(CACHE_NAME);
    const saved = new Set((await cache.keys()).map(request => new URL(request.url).pathname));
    const missing = OFFLINE.assets.filter(path => !saved.has(path));
    // addAll commits the batch only after every download succeeds. A failed
    // update leaves the previous, complete offline copy available.
    if (missing.length) await cache.addAll(missing.map(path => new Request(path, { cache: 'reload' })));
  })().finally(() => { preparing = undefined; });
}

self.addEventListener('install', event => {
  event.waitUntil(prepare());
  // Let an existing journey finish before activating an update. Never reload
  // a listener's page or stop their audio to replace the offline copy.
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) {
      if (name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME) await caches.delete(name);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type !== 'PREPARE_OFFLINE' || !event.ports[0]) return;
  event.waitUntil(prepare().then(
    () => event.ports[0].postMessage({ ready: true }),
    () => event.ports[0].postMessage({ ready: false }),
  ));
});

async function navigation(request) {
  const cache = await caches.open(CACHE_NAME);
  const saved = await cache.match(OFFLINE.shell);
  if (saved && self.navigator.onLine === false) return saved;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 3000);
  try {
    const response = await fetch(request, { signal: controller.signal });
    if (response.status >= 500 && saved) return saved;
    return response;
  } catch (error) {
    if (saved) return saved;
    throw error;
  } finally {
    clearTimeout(timeout);
  }
}

async function asset(request, path) {
  const current = await caches.open(CACHE_NAME);
  const saved = await current.match(path);
  if (saved) return saved;
  // An online navigation can load a newer page while its worker is waiting.
  // Its hashed chunks may already be downloaded in that waiting worker's cache.
  if (path.startsWith('/_next/static/')) {
    for (const name of await caches.keys()) {
      if (!name.startsWith(CACHE_PREFIX) || name === CACHE_NAME) continue;
      const cached = await (await caches.open(name)).match(path);
      if (cached) return cached;
    }
  }
  return fetch(request);
}

self.addEventListener('fetch', event => {
  const { request } = event;
  const url = new URL(request.url);
  // Accounts, room state, API writes, Anki and external streams always use the
  // network. Only the public app shell and its build assets belong in this cache.
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (request.mode === 'navigate' && (url.pathname === '/' || url.pathname === '/index.html')) {
    event.respondWith(navigation(request));
  } else if (ASSETS.has(url.pathname) || url.pathname.startsWith('/_next/static/')) {
    event.respondWith(asset(request, url.pathname));
  }
});
